services:
  db:
    image: postgres:15
    container_name: RVParkDB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbpassword}
      POSTGRES_DB: ${POSTGRES_DB:-RVParkDB}
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - rvpark_data:/var/lib/postgresql/data  # Add this line
    command: 
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_statement=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rvpark_data: